In [3]:
# broadcast scalar to one-dimensional array
from numpy import array
# define array
a = array([1, 2, 3])
print(a)
# define scalar
b = 2
print(b)
# broadcast
c = a + b
print(c)

[1 2 3]
2
[3 4 5]


In [4]:
#Scalar and Two-Dimensional Array
# broadcast scalar to two-dimensional array
from numpy import array
# define array
A = array([
[1, 2, 3],
[1, 2, 3]])
print(A)
# define scalar
b = 2
print(b)
# broadcast
C = A + b
print(C)

[[1 2 3]
 [1 2 3]]
2
[[3 4 5]
 [3 4 5]]


In [5]:
#One-Dimensional and Two-Dimensional Arrays
# broadcast one-dimensional array to two-dimensional array
from numpy import array
# define two-dimensional array
A = array([
[1, 2, 3],
[1, 2, 3]])
print(A)
# define one-dimensional array
b = array([4, 5, 6])
print(b)
# broadcast
C = A + b
print(C)

[[1 2 3]
 [1 2 3]]
[4 5 6]
[[5 7 9]
 [5 7 9]]


In [6]:
#Limitations of Broadcasting
from numpy import array
# define two-dimensional array
A = array([
[1, 2, 3],
[1, 2, 3]])
print(A.shape)
# define one-dimensional array
b = array([1, 2])
print(b.shape)
# attempt broadcast
C = A + b
print(C)

(2, 3)
(2,)


ValueError: operands could not be broadcast together with shapes (2,3) (2,) 