In [2]:
#Elementwise operations

#With Scalars
import numpy as np
a = np.array([9, 8, 7, 6])
print(a+1)
print(2*a)

[10  9  8  7]
[18 16 14 12]


In [5]:
#Arithemetic operations are elementwise
b = np.ones(4) + 1
print(a - b)
print(a * b)
j=np.arange(5)
print(j)
print(2**(j + 2) + j)

[7. 6. 5. 4.]
[18. 16. 14. 12.]
[0 1 2 3 4]
[ 4  9 18 35 68]


In [8]:
#Array multiplications is not a matrix multiplications
c=np.ones((3,3))
print(c*c)
print(a*a)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
[81 64 49 36]


In [9]:
#Matrix multiplication
c.dot(c)

array([[3., 3., 3.],
       [3., 3., 3.],
       [3., 3., 3.]])

In [12]:
#Comparison operators
a = np.array([1, 2, 3, 4])
b = np.array([4, 2, 2, 4])
print(a == b)
print(a>b)

[False  True False  True]
[False False  True False]


In [15]:
#Array-wise comparisons
a = np.array([1, 2, 3, 4])
b = np.array([4, 2, 2, 4])
c = np.array([9, 8, 7, 6])
d=np.array([1,2,3,4])
print(np.array_equal(a,b))
print(np.array_equal(a, c))
print(np.array_equal(a,d))

False
False
True


In [18]:
#Logical operations
a = np.array([1, 1, 0, 0], dtype=bool)
b = np.array([1, 0, 1, 0], dtype=bool)
print(np.logical_or(a, b))
print(np.logical_and(a, b))

[ True  True  True False]
[ True False False False]


In [20]:
#Transcendental functions:
a=np.arange(5)
print(np.sin(a))
print(np.log(a))
print(np.exp(a))

[ 0.          0.84147098  0.90929743  0.14112001 -0.7568025 ]
[      -inf 0.         0.69314718 1.09861229 1.38629436]
[ 1.          2.71828183  7.3890561  20.08553692 54.59815003]


C:\Users\Saurav Anand\Anaconda3\lib\site-packages\ipykernel_launcher.py:4: RuntimeWarning: divide by zero encountered in log
  after removing the cwd from sys.path.


In [21]:
#Shape mismatches
a = np.arange(4)
a + np.array([1, 2])

ValueError: operands could not be broadcast together with shapes (4,) (2,) 

In [23]:
#Transposition
a = np.triu(np.ones((3, 3)), 1)
print(a)
print(a.T)

[[0. 1. 1.]
 [0. 0. 1.]
 [0. 0. 0.]]
[[0. 0. 0.]
 [1. 0. 0.]
 [1. 1. 0.]]


In [24]:
#Transposition is a view , following code will fail
a+=a.T
#It will work for small arrays (because of buffering) but fail for large one, in unpredictable ways

In [26]:
#Computing sums
x=np.array([1,2,3,4])
print(np.sum(x))
print(x.sum())


10
10


In [31]:
#sum by rows and columns
x = np.array([[1, 1], [2, 2]])
print(x)
# columns (first dimension)
print(x.sum(axis=0))
print(x[:, 0].sum())
print(x[:, 1].sum())

#row (second dimension)
y=np.array([[2,4],[3,6]])
print(y[0, :].sum())
print(y[1, :].sum())

[[1 1]
 [2 2]]
[3 3]
3
3
6
9


In [33]:
#Extrema
x=np.array([1,3,5])
print(x.min())
print(x.max())
#index of mine
print(x.argmin())
#index of maximum
print(x.argmax())



1
5
0
2


In [37]:
#logical operations
print(np.all([True, True, False]))
print(np.any([True, True, False]))

#used for array comparison
a = np.zeros((100, 100))
print(np.any(a != 0))
print(np.all(a == a))


a = np.array([1, 2, 3, 2])
b = np.array([2, 2, 3, 2])
c = np.array([6, 4, 4, 5])
print(((a <= b) & (b <= c)).all())

False
True
False
True
True


In [39]:
#Statistics
x = np.array([1, 2, 3, 1])
y=  np.array([[1, 2, 3], [5, 6, 1]])
print(x.mean())
print(np.median(x))
#last axis
print(np.median(y,axis=-1))
#full population standard deviation
print(x.std())

1.75
1.5
[2. 5.]
0.82915619758885


In [40]:
#Bigger type wins in the case of mixed type operations:
z=np.array([1,2,3])+1.5
print(z)

[2.5 3.5 4.5]


In [41]:
#Assignment never changes the type!
a=np.array([1,2,3])
print(a.dtype)
a[0]=2.3 #float is truncated to integer
print(a)

int32
[2 2 3]


In [42]:
#Forced casts
a=np.array([1.7,1.2,1.6])
# <-- truncates to integer
b = a.astype(int)
print(b)

[1 1 1]


In [43]:
#Rounding
a = np.array([1.2, 1.5, 1.6, 2.5, 3.5, 4.5])
b = np.around(a)
#still floating point 
print(b)
c=np.around(a).astype(int)
print(c)

[1. 2. 2. 2. 4. 4.]
[1 2 2 2 4 4]
