In [2]:
#Stack flat arrays in columns:
import numpy as np
a=np.array([0,1])
b=np.array([2,3])
ab=np.stack((a,b))
print(ab)

[[0 1]
 [2 3]]


In [3]:
#use of vstack method to stack arrays vertically
x=np.array([1,2,3])
y=np.array([4,5,6])
z=np.vstack((x,y))
print(z)

[[1 2 3]
 [4 5 6]]


In [8]:
#Use of hstack method to stack arrays horizontally
p=np.array([7,8,9])
q=np.array([10,11,12])
r=np.hstack((p,q))
print(r)

[ 7  8  9 10 11 12]
