In [5]:
#one dimensional indexing
import numpy as np
data=[11,22,33,44,55,66]
arr1=np.array(data)
print(arr1)

#first element
print(arr1[0])

#last element can be represented by -1 or ( size-1 )index
print(arr1[-1])

[11 22 33 44 55 66]
11
66


In [6]:
#Index out of bound error
print(arr1[7])

IndexError: index 7 is out of bounds for axis 0 with size 6

In [13]:
#Two Dimensional Indexing
data2=[(1,2),(3,4),(5,6),(7,8),(9,10)]
arr2=np.array(data2)
print(arr2)
print(arr2[0,1])
print(arr2[1,0])
print(arr2[3,1])

[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]]
2
3
8


In [15]:
#prints all the items in the first row
print(arr2[0,])

[1 2]


In [24]:
#one dimensional slicing
print(arr1)
# Grab index 1 and everything past it
print(arr1[1:])
#Grab everything UP TO index 3
print(arr1[:3])
#random slicing
print(arr1[1:2])
print(arr1[2:3])

[11 22 33 44 55 66]
[22 33 44 55 66]
[11 22 33]
[22]
[33]


In [32]:
#negative index slicing in one dimensional arrays

#print the last element
print(arr1[-1:])
#print the last two elements
print(arr1[-2:])
#random slicing using negative index
print(arr1[-2:-1])
print(arr1[-5:-4])

[66]
[55 66]
[55]
[22]


In [34]:
#Slicing in 2-dimensional array
X=arr2[:,:-1]
y=arr2[:,-1]
print(X)
print(y)

[[1]
 [3]
 [5]
 [7]
 [9]]
[ 2  4  6  8 10]


In [49]:
#Array reshaping
#shape attribute that returns a tuple of the length of each dimension of the array
# reshape 1D array to 2D
from numpy import array
# define array
data = array([11, 22, 33, 44, 55])
print(data.shape)
# reshape
data = data.reshape((data.shape[0], 1))
print(data.shape)

(5,)
(5, 1)


In [38]:
#shape of a two-dimensional array
print(arr2)
print(arr2.shape)

[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]]
(5, 2)


In [48]:
#reshape from two-dimension to 3-dimension array
from numpy import array
# list of data
data = [[11, 22],
[33, 44],
[55, 66]]
# array of data
data = array(data)
print(data.shape)
# reshape
data = data.reshape((data.shape[0], data.shape[1], 1))
print(data.shape)

(3, 2)
(3, 2, 1)
