In [1]:
#import libraries
import numpy as np
#Create a one dimentional Array
data1= [1,2,3,4]
arr1=np.array(data1)

In [2]:
arr1

array([1, 2, 3, 4])

In [3]:
#create a 2-dimensional data 
data2=[range(2,6),range(5,9)]
arr2=np.array(data2)

In [5]:
arr2

array([[2, 3, 4, 5],
       [5, 6, 7, 8]])

In [6]:
#create a empty array
arr3=np.empty([2,2])

In [7]:
arr3

array([[6.23042070e-307, 4.67296746e-307],
       [1.69121096e-306, 1.02360460e-306]])

In [9]:
#create an empty like array
x=[1,2,3,8]
arr4=np.empty_like(x)

In [12]:
arr4

array([         0,          0, -281042512,        439])

In [13]:
#create zeroes array
arr5=np.zeros(5)
print(arr5)

[0. 0. 0. 0. 0.]


In [14]:
#create a two-dimentional zeroes array
arr6=np.zeros([3,2])
print(arr6)

[[0. 0.]
 [0. 0.]
 [0. 0.]]


In [20]:
#create a zeroes-like array
y=np.arange(6)
y=y.reshape((2,3))
y
arr7=np.zeros_like(y)
arr7

array([[0, 0, 0],
       [0, 0, 0]])

In [21]:
#create ones 1-dimensional array
arr8=np.ones(6)
arr8

array([1., 1., 1., 1., 1., 1.])

In [23]:
#create ones 2-dimensional array
arr9=np.ones([4,3])
arr9

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [24]:
#creating ones-like array
x=np.arange(6)
x=x.reshape((2,3))
arr10=np.ones_like(x)
arr10

array([[1, 1, 1],
       [1, 1, 1]])

In [25]:
#data type of array
arr1.dtype

dtype('int32')

In [33]:
arr2

array([[2, 3, 4, 5],
       [5, 6, 7, 8]])

In [26]:
#shape of the array
arr2.shape

(2, 4)

In [27]:
#No of dimensions
arr3.ndim

2

In [32]:
#To get the total no of elements
arr2.size

8

In [34]:
#size of first dimension
len(arr2)

2

In [36]:
arr1

array([1, 2, 3, 4])

In [38]:
#Reshaping the array
arr = np.arange(10, dtype=float).reshape((2, 5))
print(arr.shape)
print(arr.reshape(5,2))

(2, 5)
[[0. 1.]
 [2. 3.]
 [4. 5.]
 [6. 7.]
 [8. 9.]]


In [39]:
#Add an axis
a=np.array([0,1])
a_col=a[:,np.newaxis]
print(a_col)

[[0]
 [1]]


In [41]:
#Transpose
print(a_col.T)

[[0 1]]


In [42]:
#Flatten method always returna a flat copy of the original array
arr_flt = arr.flatten()
arr_flt[0] = 33
print(arr_flt)
print(arr)

[33.  1.  2.  3.  4.  5.  6.  7.  8.  9.]
[[0. 1. 2. 3. 4.]
 [5. 6. 7. 8. 9.]]


In [43]:
#Ravel method returns the original array whenver possible
arr_flt = arr.ravel()
arr_flt[0] = 33
print(arr_flt)
print(arr)

[33.  1.  2.  3.  4.  5.  6.  7.  8.  9.]
[[33.  1.  2.  3.  4.]
 [ 5.  6.  7.  8.  9.]]
